export const fullStackDeveloperCourseData = {
  course: {
    name: "Full Stack Developer",
    code: "FSD-PGP",
    description:
      "32-week online Full Stack Development Course with certification and 100% placement support.",
    duration: "32 weeks",
    durationISO: "P32W",
    timeRequired: "PT2H",
    mode: "online",
    language: "en",
    educationalLevel: "Professional",
    startDate: "2025-11-01",
    price: {
      original: 100000,
      discounted: 70000,
      currency: "INR",
      emi: 10000,
      discountPercentage: 28,
      validUntil: "2025-12-31",
    },
    rating: {
      value: 4.8,
      count: 1200,
      best: 5,
      worst: 1,
    },
    teaches: [
      "MongoDB",
      "Express.js",
      "React",
      "Node.js",
      "JavaScript",
      "Full Stack Development",
      "Web Development",
    ],
    features: [
      { title: "Live", subtitle: "Sessions on Zoom" },
      { title: "32 Weeks", subtitle: "Course Duration" },
      { title: "Mentorship", subtitle: "With Experienced Professionals" },
      { title: "Placement", subtitle: "100% Support till Job" },
    ],
  },
  provider: {
    name: "Edurup Learning",
    url: "https://www.edurup.in",
  },
  banner: {
    backgroundColor: "#2B1F5F",
    textColor: "white",
    cohort: "14",
    cohortStartDate: "Nov 1",
  },
  company: {
    heading: "500+ Companies have hired",
    subheading: "Edurup learners",
    marqueeImages: [
      { src: "/maurquee1.jpg", alt: "Marquee Image 1" },
      { src: "/maurquee2.jpg", alt: "Marquee Image 2" },
      { src: "/maurquee3.jpg", alt: "Marquee Image 3" },
    ],
  },
  reviews: [
    {
      name: "Vansh Agrawal",
      role: "Fresher",
      from: "IIT Kharagpur",
      company: "Zomato",
      title: "Product Analyst",
      text: "I got an offer from Zomato for PA role, the learning at NextLeap helped me a lot. Thank you for the course and all the learning",
      profile: "/person1.jpg",
      fromLogo: "/iit.png",
      companyLogo: "/zomato.png",
    },
    {
      name: "Vanshu Saini",
      role: "JM Financial Ltd",
      from: "Product Management Intern",
      company: "Phenom",
      title: "Product Analyst",
      text: "Great support from the team for placements. Mentor sessions were really helpful.",
      profile: "/person2.jpg",
      fromLogo: "/jm.png",
      companyLogo: "/phenom.png",
    },
    {
      name: "Ankita B",
      role: "Byjus",
      from: "Associate Manager",
      company: "Inito",
      title: "Lead Product Analyst",
      text: "Got to collaborate with brilliant minds, learned from seasoned mentors, and put my analytical skills to the test.",
      profile: "/person3.jpg",
      fromLogo: "/byjus.png",
      companyLogo: "/inito.png",
    },
  ],
  faculty: [
    {
      name: "Rupesh Kumar",
      designation: "Chief Marketing Officer",
      image: "/mentor3.jpg",
      subjects: ["Digital Marketing", "Performance Marketing"],
      socialMedia: "linkedin",
      url: "https://in.linkedin.com/in/neelam-rupesh",
      experience: "8+ Years",
      students: "2,500+",
      rating: "4.9",
      color: "blue",
    },
    {
      name: "Sirija Neelam",
      designation: "Data Scientist",
      image: "/mentor1.jpeg",
      subjects: [
        "Python",
        "Artificial Intelligence",
        "Data Science & Machine Learning",
      ],
      socialMedia: "linkedin",
      url: "https://www.linkedin.com/in/sirija-devi-a35561160?trk=blended-typeahead",
      experience: "6+ Years",
      students: "1,800+",
      rating: "4.8",
      color: "green",
    },
    {
      name: "Mukesh Kumar",
      designation: "General Manager",
      image: "/mentor2.jpg",
      subjects: ["Digital Strategy", "Product Marketing"],
      socialMedia: "linkedin",
      url: "https://www.linkedin.com/in/askmukesh?trk=blended-typeahead",
      experience: "10+ Years",
      students: "3,200+",
      rating: "4.9",
      color: "purple",
    },
    {
      name: "Shabudeen",
      designation: "Senior Software Engineer",
      image: "/mentor4.jpg",
      subjects: ["React.js & Node.js", "Frontend Development"],
      socialMedia: null,
      url: null,
      experience: "5+ Years",
      students: "1,200+",
      rating: "4.7",
      color: "orange",
    },
  ],
  curriculum: [
    {
      title: "HTML, CSS, and Git Basics",
      duration: "2 weeks",
      lessons: "8 lessons",
      projects: "2 projects",
      description: [
        "HTML5: Structure, tags, semantic elements",
        "CSS3: Selectors, Flexbox, Grid, Responsive Design",
        "CSS Frameworks: Tailwind / Bootstrap",
        "Git & GitHub: version control, repository, branching, commits",
        "Mini Project: “Personal Portfolio Website",
      ],
    },
    {
      title: "JavaScript Fundamentals",
      duration: "3 weeks",
      lessons: "12 lessons",
      projects: "3 projects",
      description: [
        "Variables, Data Types, Operators",
        "Functions, Loops, Conditional statements",
        "Arrays, Objects, ES6+ features (let/const, arrow functions, template literals)",
        "DOM Manipulation & Events",
        "Async JS: Promises, Async/Await",
        "Mini Project: “Todo List App” (Vanilla JS)",
      ],
    },
    {
      title: "React.js Basics",
      duration: "4 weeks",
      lessons: "16 lessons",
      projects: "4 projects",
      description: [
        "React.js Basics",
        "Functional Components & Hooks (useState, useEffect)",
        "Event Handling, Lists, Conditional Rendering",
        "Folder structure & environment setup",
        "Mini Project: “Weather App using API",
      ],
    },
    {
      title: "Advanced React",
      duration: "3 weeks",
      lessons: "14 lessons",
      projects: "3 projects",
      description: [
        "Advanced React",
        "State Management with Redux Toolkit (optional)",
        "API Integration with Axios / Fetch",
        "Reusable components & UI design systems",
        "Project 1: “E-commerce Frontend with React",
      ],
    },
    {
      title: "Node.js Fundamentals",
      duration: "2 weeks",
      lessons: "10 lessons",
      projects: "2 projects",
      description: [
        "Node.js Fundamentals",
        "File System, Event Loop, Async Programming",
        "Express.js introduction, Routes & Middleware",
        "REST API basics",
        "Mini Project: “Simple CRUD API",
      ],
    },
    {
      title: "MongoDB & Mongoose",
      duration: "1 week",
      lessons: "6 lessons",
      projects: "1 project",
      description: [
        "NoSQL vs SQL databases",
        "MongoDB CRUD Operations",
        "Mongoose Schema, Models, and Validation",
        "Relationship between collections (One-to-Many)",
        "Mini Project: “Student Management API",
      ],
    },
    {
      title: "Authentication & Authorization",
      duration: "1 week",
      lessons: "6 lessons",
      projects: "1 project",
      description: [
        "JWT Authentication & Security concepts",
        "Password Hashing (bcrypt)",
        "Login/Signup functionality",
        "Protecting routes & middleware authentication",
        "Project 2: “User Auth System with JWT",
      ],
    },
    {
      title: "Advanced Backend",
      duration: "1 week",
      lessons: "6 lessons",
      projects: "1 project",
      description: [
        "File uploads (Multer/Cloudinary)",
        "Error handling & validation",
        " Environment variables (.env)",
        " API documentation using Postman / Swagger",
        " Deploying backend on Render / Railway",
        "Project 3: “Blog API”",
      ],
    },
    {
      title: "MERN Integration",
      duration: "1 week",
      lessons: "6 lessons",
      projects: "1 project",
      description: [
        "Connecting React frontend with Node.js backend",
        "Using Axios for API calls",
        "Handling CORS & environment setup",
        "Authentication flow (Login/Logout on both sides)",
        " Mini Project: “Notes App (Full Stack)”",
      ],
    },
    {
      title: "Real-World Full Stack Project",
      duration: "1 week",
      lessons: "6 lessons",
      projects: "1 project",
      description: [
        "Project planning & folder structuring",
        "Role-based authentication",
        " CRUD Operations on both sides",
        " Integrating image uploads, pagination, filters",
        " Project 4: “Job Portal / Task Manager / E-Commerce App”",
      ],
    },
    {
      title: "Deployment & DevOps Basics",
      duration: "1 week",
      lessons: "6 lessons",
      projects: "1 project",
      description: [
        "Deploying React app on Netlify/Vercel",
        " Deploying backend on Render/Railway",
        " Connecting MongoDB Atlas",
        " Environment management, SSL, Domain setup",
        // note: CI/CD line removed in source; keep as data-neutral
      ],
    },
    {
      title: "Interview & Placement Preparation",
      duration: "1 week",
      lessons: "6 lessons",
      projects: "1 project",
      description: [
        " Resume & LinkedIn optimization",
        " GitHub Portfolio & Projects review",
        " Common MERN interview questions",
        " Mock interviews, coding tests, and DSA basics",
        " Final Project Presentation & Demo Day",
      ],
    },
  ],
  fee: {
    scholarship: {
      percentage: 30,
      originalPrice: 100000,
      discountedPrice: 70000,
      emi: 10000,
      gst: true,
    },
    features: [
      {
        description: "Spend only two hours/day",
        icon: "Clock",
        color: "text-blue-600",
      },
      {
        description: "One-on-one mentorship and doubt resolution",
        icon: "Users",
        color: "text-green-600",
      },
      {
        description: "Network with your peers and industry experts",
        icon: "GraduationCap",
        color: "text-purple-600",
      },
      {
        description: "Job Guaranteed with Placement Services",
        icon: "Shield",
        color: "text-orange-600",
      },
    ],
    badge: "Most Popular",
    cta: {
      text: "Apply Now - Limited Seats Available",
      note: "⚡ Scholarship applications closing soon",
    },
  },
  language: {
    heading: "Learning Journey",
    title: "Learn all the Tools that are In-demand",
    tools: [
      {
        name: "VS Code",
        icon: "/Language/vscode.png",
        color: "bg-blue-100 text-blue-700",
      },
      {
        name: "GitHub",
        icon: "/Language/github.png",
        color: "bg-gray-100 text-gray-700",
      },
      {
        name: "Node.js",
        icon: "/Language/node.png",
        color: "bg-green-100 text-green-700",
      },
      {
        name: "MongoDB",
        icon: "/Language/mongo.png",
        color: "bg-emerald-100 text-emerald-700",
      },
      {
        name: "Express.js",
        icon: "/Language/express.png",
        color: "bg-gray-100 text-gray-700",
      },
      {
        name: "React",
        icon: "/Language/react.png",
        color: "bg-cyan-100 text-cyan-700",
      },
      {
        name: "Postman",
        icon: "/Language/postman.png",
        color: "bg-orange-100 text-orange-700",
      },
      {
        name: "Redux",
        icon: "/Language/redux1.png",
        color: "bg-purple-100 text-purple-700",
      },
      {
        name: "Docker",
        icon: "/Language/docker.png",
        color: "bg-blue-100 text-blue-700",
      },
      {
        name: "Vercel",
        icon: "/Language/vercel.png",
        color: "bg-black-100 text-black-700",
      },
    ],
  },
  learning: {
    heading: "Learning Journey",
    title: "The New Immersive Learning Experience",
    description:
      "Follow our structured learning path from enrollment to job placement",
    steps: [
      {
        title: "Start Learning",
        description: [
          "Pay 70,000 and join the course",
          "Live Classes by Experts",
        ],
        image: "/learning1.svg",
      },
      {
        title: "Get Assessed",
        description: [
          "Write Online Assessment",
          "Get Eligibility for placements",
        ],
        image: "/learning2.svg",
      },
      {
        title: "Apply for jobs",
        description: [
          "Access Placement videos",
          "Apply for Jobs",
          "Get an offer letter",
        ],
        image: "/learning3.svg",
      },
    ],
  },
  placementAssistance: {
    heading: "Placement Assistance",
    description:
      "Stand out from your peers in front of the recruiters and start your career.",
    features: [
      { icon: "Code", title: "One-on-one Sessions" },
      { icon: "LineChart", title: "Career Guidance" },
      { icon: "Briefcase", title: "300+ Hiring Partners" },
      { icon: "GanttChartSquare", title: "Resume Building" },
      { icon: "ScrollText", title: "Mock Interviews" },
      { icon: "UserRoundCog", title: "Soft Skills Training" },
    ],
    image: "/banner-01-2.png",
  },
  productAnalyst: {
    heading: "Your Future Job Title",
    titles: [
      "Marketing\nAnalyst",
      "Data\nAnalyst",
      "Business\nAnalyst",
      "Product\nAnalyst",
    ],
    salaries: {
      average: "8-10 Lakhs",
      highest: "31 Lakhs",
      highestCompany: "Top Firms",
    },
  },
  faq: [
    {
      question:
        "What is the Full Stack Developer Course offered by Edurup Learning in {city}?",
      answer:
        "The Full Stack Developer Course in {city} by Edurup Learning is a job-ready, industry-oriented program covering front-end and back-end with live projects and placement support.",
    },
    {
      question: "Who can apply for the Full Stack Developer course in {city}?",
      answer:
        "Fresh graduates, working professionals, and non-IT learners. No strict prior coding required.",
    },
  ],
};
