export const dataAnalyticsCourseData = {
  course: {
    name: "Data Analytics",
    code: "DA-PGP",
    description:
      "32-week online Data Analytics Course with Certification and 100% Placement Support.",
    duration: "32 weeks",
    durationISO: "P32W",
    timeRequired: "PT2H",
    mode: "online",
    language: "en",
    educationalLevel: "Professional",
    startDate: "2025-11-01",
    price: {
      original: 100000,
      discounted: 70000,
      currency: "INR",
      emi: 10000,
      discountPercentage: 28,
      validUntil: "2025-12-31",
    },
    rating: {
      value: 4.8,
      count: 1250,
      best: 5,
      worst: 1,
    },
    features: [
      { title: "Live", subtitle: "Sessions on Zoom" },
      { title: "32 Weeks", subtitle: "Course Duration" },
      { title: "Mentorship", subtitle: "With Experienced Professionals" },
      { title: "Placement", subtitle: "100% Support till Job" },
    ],
    teaches: [
      "Excel",
      "SQL",
      "Statistics",
      "Power BI",
      "Tableau",
      "Python",
      "EDA",
      "Data Visualization",
    ],
  },
  provider: {
    name: "Edurup Learning",
    url: "https://www.edurup.in",
    sameAs: [
      "https://www.instagram.com/edurup_learning/",
      "https://www.linkedin.com/school/edurup-learning/",
      "https://www.facebook.com/eduruplearning",
    ],
  },
  banner: {
    backgroundColor: "#2B1F5F",
    textColor: "white",
    cohort: "14",
    cohortStartDate: "Nov 1",
  },
  company: {
    heading: "500+ Companies have hired",
    subheading: "Edurup learners",
    marqueeImages: [
      { src: "/maurquee1.jpg", alt: "Marquee Image 1" },
      { src: "/maurquee2.jpg", alt: "Marquee Image 2" },
      { src: "/maurquee3.jpg", alt: "Marquee Image 3" },
    ],
  },
  reviews: [
    {
      name: "Vansh Agrawal",
      role: "Fresher",
      from: "IIT Kharagpur",
      company: "Zomato",
      title: "Product Analyst",
      text: "I got an offer from Zomato for PA role, the learning at NextLeap helped me a lot. Thank you for the course and all the learning.",
      profile: "/person1.jpg",
      fromLogo: "/iit.png",
      companyLogo: "/zomato.png",
    },
    {
      name: "Vanshu Saini",
      role: "JM Financial Ltd",
      from: "Product Management Intern",
      company: "Phenom",
      title: "Product Analyst",
      text: "Great support from the team for placements. Mentor sessions were really helpful.",
      profile: "/person2.jpg",
      fromLogo: "/jm.png",
      companyLogo: "/phenom.png",
    },
    {
      name: "Ankita B",
      role: "Byjus",
      from: "Associate Manager",
      company: "Inito",
      title: "Lead Product Analyst",
      text: "Got to collaborate with brilliant minds, learned from seasoned mentors, and put my analytical skills to the test.",
      profile: "/person3.jpg",
      fromLogo: "/byjus.png",
      companyLogo: "/inito.png",
    },
  ],
  faculty: [
    {
      name: "Sirija Devi",
      designation: "Data Analyst",
      image: "/sirija.png",
      subjects: ["Python", "SQL", "Power BI", "Excel"],
      socialMedia: "linkedin",
      url: "https://www.linkedin.com/in/sirija-devi-a35561160?trk=blended-typeahead",
      experience: "4+ Years",
      students: "1,800+",
      rating: "4.8",
      color: "green",
    },
  ],
  curriculum: [
    {
      title: "Python Fundamentals",
      duration: "2 weeks",
      lessons: "10 lessons",
      projects: "1 mini project",
      description: [
        "Python Basics: Syntax, Variables, Data Types",
        "Conditional Statements, Loops, Functions",
        "Lists, Tuples, Sets, Dictionaries",
        "File Handling & Exception Handling",
        'Mini Project: "Student Result Calculator"',
      ],
    },
    {
      title: "Data Analysis with NumPy & Pandas",
      duration: "3 weeks",
      lessons: "12 lessons",
      projects: "1 mini project",
      description: [
        "NumPy Arrays, Operations, Broadcasting",
        "Pandas DataFrames, Series, Indexing",
        "Data Cleaning, Handling Missing Values, Filtering",
        "Merging, Grouping, and Aggregations",
        'Mini Project: "Analyze Sales Data (Excel/CSV)"',
      ],
    },
    {
      title: "Data Visualization",
      duration: "2 weeks",
      lessons: "10 lessons",
      projects: "1 project",
      description: [
        "Matplotlib & Seaborn for plotting",
        "Line, Bar, Pie, Scatter, Heatmaps",
        "Real-world dataset visualization (Kaggle Datasets)",
        'Project: "Exploratory Data Analysis on Covid / Netflix Dataset"',
      ],
    },
    {
      title: "Statistics & Probability for Data Science",
      duration: "2 weeks",
      lessons: "10 lessons",
      projects: "1 project",
      description: [
        "Descriptive Statistics (Mean, Median, Mode, Variance, SD)",
        "Probability, Permutations & Combinations",
        "Correlation, Covariance",
        "Normal Distribution, Hypothesis Testing (t-test, chi-square)",
        'Project: "Statistical Analysis on Real Dataset"',
      ],
    },
    {
      title: "Introduction to Machine Learning",
      duration: "2 weeks",
      lessons: "10 lessons",
      projects: "1 mini project",
      description: [
        "What is ML? Supervised vs Unsupervised Learning",
        "Data Preprocessing: Encoding, Scaling, Splitting",
        "Evaluation Metrics: Accuracy, Precision, Recall, F1",
        "ML Pipeline & Workflow",
        'Mini Project: "Predict Student Scores"',
      ],
    },
    {
      title: "Supervised Learning – Regression",
      duration: "2 weeks",
      lessons: "8 lessons",
      projects: "1 project",
      description: [
        "Linear Regression, Polynomial Regression",
        "Ridge & Lasso Regularization",
        "Model Evaluation: R², RMSE",
        'Project: "House Price Prediction"',
      ],
    },
    {
      title: "Supervised Learning – Classification",
      duration: "3 weeks",
      lessons: "12 lessons",
      projects: "1 project",
      description: [
        "Logistic Regression, KNN, Decision Tree, Random Forest",
        "SVM, Naïve Bayes",
        "Cross Validation & Hyperparameter Tuning (GridSearchCV)",
        'Project: "Loan Approval / Diabetes Prediction"',
      ],
    },
    {
      title: "Unsupervised Learning",
      duration: "2 weeks",
      lessons: "10 lessons",
      projects: "1 project",
      description: [
        "Clustering: K-Means, Hierarchical",
        "Dimensionality Reduction: PCA",
        "Anomaly Detection & Customer Segmentation",
        'Project: "Customer Segmentation for Marketing"',
      ],
    },
    {
      title: "Introduction to Neural Networks",
      duration: "2 weeks",
      lessons: "10 lessons",
      projects: "1 project",
      description: [
        "What is Deep Learning? Perceptron Concept",
        "Activation Functions (ReLU, Sigmoid, Softmax)",
        "Building Neural Networks with TensorFlow/Keras",
        'Project: "Handwritten Digit Recognition (MNIST)"',
      ],
    },
    {
      title: "Convolutional Neural Networks (CNN)",
      duration: "2 weeks",
      lessons: "8 lessons",
      projects: "1 project",
      description: [
        "Image Data Preprocessing",
        "CNN Architecture (Conv, Pooling, Flatten, Dense)",
        "Data Augmentation",
        'Project: "Image Classification using CNN"',
      ],
    },
    {
      title: "Natural Language Processing (NLP)",
      duration: "2 weeks",
      lessons: "8 lessons",
      projects: "1 project",
      description: [
        "Text Preprocessing (Tokenization, Lemmatization)",
        "Bag of Words, TF-IDF",
        "Sentiment Analysis with Logistic Regression",
        'Project: "Twitter Sentiment Analysis / Movie Review Classification"',
      ],
    },
    {
      title: "Model Deployment & Career Readiness",
      duration: "2 weeks",
      lessons: "10 lessons",
      projects: "1 final project",
      description: [
        "Flask / Streamlit for Model Deployment",
        "Deploy on Render / Hugging Face Spaces",
        "GitHub Project Upload & Documentation",
        "Resume Building & Interview Prep",
        'Final Project Demo: "AI-Powered Data Science Capstone"',
      ],
    },
    {
      title: "Final Projects (Choose Any 2–3 for Portfolio)",
      duration: "—",
      lessons: "—",
      projects: "3 projects",
      description: [
        "House Price Prediction",
        "Customer Segmentation Dashboard",
        "Sentiment Analysis (Twitter / Reviews)",
        "Image Classification (CNN)",
        "Sales Forecasting using Time Series",
      ],
    },
  ],
  fee: {
    scholarship: {
      percentage: 30,
      originalPrice: 100000,
      discountedPrice: 70000,
      emi: 10000,
      gst: true,
    },
    features: [
      {
        description: "Spend only two hours/day",
        icon: "Clock",
        color: "text-blue-600",
      },
      {
        description: "One-on-one mentorship and doubt resolution",
        icon: "Users",
        color: "text-green-600",
      },
      {
        description: "Network with your peers and industry experts",
        icon: "GraduationCap",
        color: "text-purple-600",
      },
      {
        description: "Job Guaranteed with Placement Services",
        icon: "Shield",
        color: "text-orange-600",
      },
    ],
    badge: "Most Popular",
    cta: {
      text: "Apply Now - Limited Seats Available",
      note: "⚡ Scholarship applications closing soon",
    },
  },
  language: {
    heading: "Learning Journey",
    title: "Learn all the Tools that are In-demand",
    tools: [
      {
        name: "Excel",
        icon: "/Language/excel.png",
        color: "bg-green-100 text-green-700",
      },
      {
        name: "SQL",
        icon: "/Language/sql.png",
        color: "bg-blue-100 text-blue-700",
      },
      {
        name: "Power BI",
        icon: "/Language/PowerBI.png",
        color: "bg-yellow-100 text-yellow-700",
      },
      {
        name: "Tableau",
        icon: "/Language/tableau.png",
        color: "bg-indigo-100 text-indigo-700",
      },
      {
        name: "Python",
        icon: "/Language/Python.png",
        color: "bg-emerald-100 text-emerald-700",
      },
      {
        name: "Pandas",
        icon: "/Language/Pandas.png",
        color: "bg-emerald-100 text-emerald-700",
      },
      {
        name: "NumPy",
        icon: "/Language/NumPy.png",
        color: "bg-emerald-100 text-emerald-700",
      },
      {
        name: "Matplotlib",
        icon: "/Language/Matplotlib.png",
        color: "bg-emerald-100 text-emerald-700",
      },
    ],
  },
  learning: {
    heading: "Learning Journey",
    title: "The New Immersive Learning Experience",
    description:
      "Follow our structured learning path from enrollment to job placement",
    steps: [
      {
        title: "Start Learning",
        description: [
          "Pay 70,000 and join the course",
          "Live Classes by Experts",
        ],
        image: "/learning1.svg",
      },
      {
        title: "Get Assessed",
        description: [
          "Write Online Assessment",
          "Get Eligibility for placements",
        ],
        image: "/learning2.svg",
      },
      {
        title: "Apply for jobs",
        description: [
          "Access Placement videos",
          "Apply for Jobs",
          "Get an offer letter",
        ],
        image: "/learning3.svg",
      },
    ],
  },
  placementAssistance: {
    heading: "Placement Assistance",
    description:
      "Stand out with the right skills and get your data career started.",
    features: [
      { icon: "Code", title: "One-on-one Sessions" },
      { icon: "LineChart", title: "Career Guidance" },
      { icon: "Briefcase", title: "300+ Hiring Partners" },
      { icon: "GanttChartSquare", title: "Resume Building" },
      { icon: "ScrollText", title: "Mock Interviews" },
      { icon: "UserRoundCog", title: "Soft Skills Training" },
    ],
    image: "/banner-01-2.png",
  },
  productAnalyst: {
    heading: "Your Future Job Title",
    titles: [
      "Data Analyst",
      "Business Analyst",
      "Reporting Analyst",
      "BI Analyst",
    ],
    salaries: {
      average: "8-10 Lakhs",
      highest: "31 Lakhs",
      highestCompany: "Top Firms",
    },
  },
};
